#!/usr/bin/env python

if __name__ == "__main__":
    import os
    import argparse

    parser = argparse.ArgumentParser(
        description='Keras train pairs for each layer-pairs')
    add_arg = parser.add_argument
    add_arg('input_name', type=str, help='input file name')

    args = parser.parse_args()
    input_name = args.input_name

    from trk_reco.log_parser import Match, Timing

    newStrategyInfo = Match('My')
    timing_info = Timing()

    with open(input_name) as f:
        for line in f:
            timing_info.parse(line)
            newStrategyInfo.parse(line)

    newStrategyTiming = Timing()
    for line in newStrategyInfo.out().split('\n'):
            if len(line) < 2:
                continue
            newStrategyTiming.add(line+'\n')

    df_newStrategy = newStrategyTiming.out()
    df_newStrategy['TimePerEvt'] = df_newStrategy['Total']/1998
    df_newStrategy.sort_values(by=['TimePerEvt'], ascending=False)
