#!/usr/bin/env python

if __name__ == "__main__":
    import os
    import argparse

    parser = argparse.ArgumentParser(
        description='Keras train pairs for each layer-pairs')
    add_arg = parser.add_argument
    add_arg('input_name', type=str, help='input file name')

    args = parser.parse_args()
    input_name = args.input_name

    from trk_reco.log_parser import Match, Timing

    newStrategyInfo = Match('My')
    timing_info = Timing()

    ## InDetTrackParticles Info
    inDetTrackParticlesInfo = Match('InDetTrackParticles ')
    vtxFinder = Match('InDetPriVxFinder')

    with open(input_name) as f:
        for line in f:
            timing_info.parse(line)
            newStrategyInfo.parse(line)
            inDetTrackParticlesInfo.parse(line)
            vtxFinder.parse(line)

    newStrategyTiming = Timing()
    for line in newStrategyInfo.out().split('\n'):
            if len(line) < 2:
                continue
            newStrategyTiming.add(line+'\n')

    df_newStrategy = newStrategyTiming.out()
    df_newStrategy['TimePerEvt'] = df_newStrategy['Total']/1998
    print("SiSpTrackFinder Timing")
    print(df_newStrategy.sort_values(by=['TimePerEvt'], ascending=False))

    # InDetector Timing
    df = timing_info.out()
    print("All Algorithms")
    print(df.sort_values(by=['Total'], ascending=False).head(15))

    # InDetTrackParticles
    print(inDetTrackParticlesInfo.out())

    # Vertex Finder()
    print(vtxFinder.out())
